@WebApplication1_HostAddress = http://localhost:5241

POST {{WebApplication1_HostAddress}}/api/exam
Content-Type: application/json

{
    "Name": "Egzamin testowy - middleware"
}

###

GET {{WebApplication1_HostAddress}}/api/exam

###

GET {{WebApplication1_HostAddress}}/api/exam/0

###
